language: java
sudo: false

cache:
 directories:
   - $HOME/.m2

script: mvn clean install

after_success:
  - chmod +x ./scripts/travis-after_install.sh
  - source ./scripts/travis-after_install.sh

branches:
  only:
    - master