version: '3'

services:
  maven:
    # container_name: jeopardy_maven
    image: maven:3.5-jdk-8-alpine
    volumes:
      - .:/opt/maven
    working_dir: /opt/maven
    command: ['mvn', 'clean', 'install']

  tomcat:
    build:
      context: .
      dockerfile: Dockerfile_tomcat
    # container_name: jeopardy_tomcat
    image: jeopardy_tomcat_img
    depends_on:
      - maven
    ports:
      - 8080:8080
    volumes:
      - .:/src