version: '3'

services:
  build-deploy:
    build: .
    # container_name: jeopardy_build_deploy
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=1234
    image: jeopardy_build-deploy_img
    links:
      - mysql
    ports:
      - 8080:8080
    volumes:
      - .:/src

  mysql:
    # container_name: jeopardy_mysql
    image: mysql:5.7.19
    environment:
      # If you change here, make sure to also change in:
      # src/main/java/com/jeopardyio/dao/DAO.java
      # and below under tomcat service
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - sql-datavolume:/var/lib/mysql

volumes:
  sql-datavolume: